config_map: 
  - name: PRODUCT
    value: "{{ product.name }}"
  - name: TASK_MANAGER
    value: "{{ task_manager.name }}"       
  - name: JIRA_BASE_URL
    value: "{{ jira.base_url }}" 
  - name: JBOSS_A_MQ_BROKER_URL
    value: "tcp://broker-amq-tcp.{{ project }}.svc:61616"
  - name: CONSOLE_JENKINS_API_JDBC_URL
    value: "jdbc:postgresql://postgresql.{{ project }}.svc:5432/{{ project }}-{{ microservice.name }}"
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-{{ microservice.name }}"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ product.name }}-monitoring.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ product.name }}-monitoring.svc"    